# Generated by Django 5.2.1 on 2025-05-31 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be in the format XX-XXX, e.g., 66-666', regex='^\\d{2}-\\d{3}$')])),
            ],
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
